// <auto-generated />
using System;
using B1ask1.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace B1Task1.DataAccess.Migrations
{
    [DbContext(typeof(RandomDataDbContext))]
    [Migration("20241029135652_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("B1Task1.Model.RandomDataEntry", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("DecimalNumber")
                        .HasColumnType("numeric");

                    b.Property<string>("EnglishString")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EvenNumber")
                        .HasColumnType("integer");

                    b.Property<string>("RussianString")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("RandomDataEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
